
apiVersion: v1
kind: Secret
metadata:
  name: wso2am-pattern-1-creds
  namespace: wso2
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJyZWdpc3RyeS5yYWNjb29uLmd1cnUiOnsidXNlcm5hbWUiOiJnaXRsYWItZGVwbG95LXRva2VuIiwicGFzc3dvcmQiOiIzN2hqOWV1c2I4eTJCTk5hX0FTWCIsImF1dGgiOiJaMmwwYkdGaUxXUmxjR3h2ZVMxMGIydGxiam96TjJocU9XVjFjMkk0ZVRKQ1RrNWhYMEZUV0E9PSJ9fX0="
---